import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { FC, ReactNode } from 'react';
import { Header } from '../molecules/Header';
import { Button, Icon, IconButton } from '@chakra-ui/react';
import { MdOutlineLogout } from 'react-icons/md';
import { supabase } from 'utils/supabaseClient';
import { useRouter } from 'next/router';

type LayoutProps = {
  children: ReactNode;
};
export const Layout: FC<LayoutProps> = ({ children }) => {
  const signout = async () => {
    await supabase.auth.signOut();
  };

  const { pathname } = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {pathname !== '/' && (
          <Button
            onClick={signout}
            pos="fixed"
            zIndex={10}
            top="10"
            right="10%"
            aria-label="logout button"
            variant="ghost"
          >
            <Icon as={MdOutlineLogout}  />
            Logout
          </Button>
        )}
        <Header />
        {children}
      </main>
    </>
  );
};
