import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { FC, ReactNode } from 'react';
import { Header } from '../molecules/Header';

type LayoutProps = {
  children: ReactNode;
};
export const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        {children}
      </main>
    </>
  );
};
