import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FormEventHandler, useEffect, useState } from "react";
import { deleteColorModeInLocalStorage } from "@/ui/theme";
import { Box, Input } from "@chakra-ui/react";

import { Task } from "@/components/molecules/Task";
import { TaskList } from "@/components/organisms/TaskList";
import { Header } from "@/components/molecules/Header";
import { InputTaskForm } from "@/components/organisms/InputTaskForm";

interface Task {
  id: string;
  uid: string;
  text: string;
  isDone: boolean;
  createdAt: string;
}

const taskList: Task[] = [
  {
    id: "cbwodcbodsc",
    uid: "cecbceiw61",
    text: "aaaaaaaaaaaaaaaaaaaa",
    isDone: true,
    createdAt: "2022/2/12",
  },
  {
    id: "cbwicbiwdc",
    uid: "cwcwdu121",
    text: "XXXXXXXXXXXXXXXXXXX",
    isDone: false,
    createdAt: "2022/2/13",
  },
  {
    id: "cbwicbiwddew2334c",
    uid: "cwcwdu121",
    text: "XXXXXXXXXXXXXXXXXXX",
    isDone: false,
    createdAt: "2022/2/13",
  },
  {
    id: "ceceuosx232r32rr",
    uid: "cwcwdu1sxsxs21",
    text: "XXXXXXXXXXXXXXXXXXX",
    isDone: false,
    createdAt: "2022/2/13",
  },
];

export default function Home() {
  // After 3s reset the localStorage
  // useEffect(() => {
  //   setTimeout(deleteColorModeInLocalStorage, 3000);
  // }, []);

  // const addTask = (event) => {
  //   if (event.key === "Enter") {
  //     console.log((event.target as HTMLInputElement).value);
  //     (event.target as HTMLInputElement).value = "";
  //   }
  // };

  // const handleSubmit: FormEventHandler<HTMLFormElement> = (event) => {
  //   event.preventDefault();
  //   const { value: task } = (event.target as any).task;
  //   console.log(task);
  //   (event.target as any).task.value = "";
  // };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <TaskList taskList={taskList} />
        <Box pos="fixed" zIndex={10} bottom="20">
          <InputTaskForm />
        </Box>
      </main>
    </>
  );
}
