import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { deleteColorModeInLocalStorage } from "@/ui/theme";
import {
  Box,
  Flex,
  Heading,
  Input,
  Stack,
  StackDivider,
  Text,
  Icon,
  Center,
  HStack,
  Spacer,
} from "@chakra-ui/react";
import { BiCheckCircle } from "react-icons/bi";
import { DeleteIcon } from "@chakra-ui/icons";

export default function Home() {
  // After 3s reset the localStorage
  // useEffect(() => {
  //   setTimeout(deleteColorModeInLocalStorage, 3000);
  // }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Heading>
          TodoApp&nbsp;By&nbsp;
          <Text as="span" color="green.400">
            Supabase
          </Text>
        </Heading>

        <Stack divider={<StackDivider />} spacing="4" w="600px">
          <Flex>
            <Center mr={4}>
              <Icon as={BiCheckCircle} w={6} h={6} color="green.700" />
            </Center>
            <Box>
              <Heading size="sm">猫ちゃんとお昼寝</Heading>
              <Text fontSize="sm" color="gray.500">
                2022/1/21
              </Text>
            </Box>
            <Spacer />
            <Center>
              <DeleteIcon w={5} h={5} color="red.700" />
            </Center>
          </Flex>

          <Flex>
            <Center mr={4}>
              <Icon as={BiCheckCircle} w={6} h={6} color="gray.600" />
            </Center>
            <Box>
              <Heading size="sm">猫ちゃんとお昼寝</Heading>
              <Text fontSize="sm" color="gray.500">
                2022/1/21
              </Text>
            </Box>
            <Spacer />
            <Center>
              <DeleteIcon w={5} h={5} color="red.700" />
            </Center>
          </Flex>

          <Flex>
            <Center mr={4}>
              <Icon as={BiCheckCircle} w={6} h={6} color="green.700" />
            </Center>
            <Box>
              <Heading size="sm">猫ちゃんとお昼寝</Heading>
              <Text fontSize="sm" color="gray.500">
                2022/1/21
              </Text>
            </Box>
            <Spacer />
            <Center>
              <DeleteIcon w={5} h={5} color="red.700" />
            </Center>
          </Flex>

          <Flex>
            <Center mr={4}>
              <Icon as={BiCheckCircle} w={6} h={6} color="green.700" />
            </Center>
            <Box>
              <Heading size="sm">猫ちゃんとお昼寝</Heading>
              <Text fontSize="sm" color="gray.500">
                2022/1/21
              </Text>
            </Box>
            <Spacer />
            <Center>
              <DeleteIcon w={5} h={5} color="red.700" />
            </Center>
          </Flex>
          <Flex>
            <Center mr={4}>
              <Icon as={BiCheckCircle} w={6} h={6} color="green.700" />
            </Center>
            <Box>
              <Heading size="sm">猫ちゃんとお昼寝</Heading>
              <Text fontSize="sm" color="gray.500">
                2022/1/21
              </Text>
            </Box>
            <Spacer />
            <Center>
              <DeleteIcon w={5} h={5} color="red.700" />
            </Center>
          </Flex>
          <Flex>
            <Center mr={4}>
              <Icon as={BiCheckCircle} w={6} h={6} color="green.700" />
            </Center>
            <Box>
              <Heading size="sm">猫ちゃんとお昼寝</Heading>
              <Text fontSize="sm" color="gray.500">
                2022/1/21
              </Text>
            </Box>
            <Spacer />
            <Center>
              <DeleteIcon w={5} h={5} color="red.700" />
            </Center>
          </Flex>
        </Stack>
        <Input placeholder="新しいタスクを入力..." w="600px" />
      </main>
    </>
  );
}
